<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
 
	<ItemGroup>
    <ProjectReference Include="..\Basket.Core\Basket.Core.csproj" />
	  <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />

	  <PackageReference Include="AutoMapper" Version="12.0.1" />
	  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
	  <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\Discount.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
